before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"
  - chmod +x ./gradlew || echo "Couldn't chmod gradlew. Exit code: $?"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

image: gradle:6.3.0-jdk8

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    when: on_failure
    name: "ktlint_${CI_COMMIT_REF_NAME}"
    expire_in: 1 days
    paths:
      - build/reports/ktlint/*.xml

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
