before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"
  - chmod +x ./gradlew || echo "Couldn't chmod gradlew. Exit code $?"

variables:
  GRADLE_OPTS: "-Dorg.gradle.parallel=true -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.caching=true"

image: gradle:6.3.0-jdk8

cache:
  paths:
    - .gradle
    - build

stages:
  - test

check:
  stage: test
  script:
    - ./gradlew check
